python3 run_seq2seq.py \
    --model_type unilm \
    --model_name_or_path unilm_base/ \
    --data_dir data/ \
    --src_file train_data.json \
    --output_dir output/ \
    --max_seq_length 512 \
    --max_position_embeddings 512 \
    --do_train \
    --do_lower_case \
    --train_batch_size 16 \
    --learning_rate 1e-5 \
    --num_train_epochs 3
